### ISSUE TITLE
PHP notice after the block is added to a page

### ISSUE THREAD

**Issue by mudrd8mz** [eLearnTK/search_course_category#1]
On the site front page, when I turn editing on and add the block instance, I start to see the PHP notice

```
Notice: Undefined property: stdClass::$text
  in blocks/search_course_category/block_search_course_category.php on line 43
```

**Comment by eLearnTK** [comment]
Undefined property fixed:
$this->content         = new stdClass;
$this->content->text   = '';

**Comment by eLearnTK** [comment]
Undefined property fixed:
$this->content = new stdClass;
$this->content->text = '';
