### ISSUE TITLE
SQL injection vulnerability

### ISSUE THREAD

**Issue by mudrd8mz** [eLearnTK/search_course_category#3]
I think that the search_course_category.php script is vulnerable to SQL injection. The input parameter `$search` (typed as PARAM_RAW) is directly used as a part of the SQL query:
```
    $select = "name LIKE '%".$search."%'";
    $table  = 'course_categories';
    $records = $DB->get_records_select($table,$select);
```
For security and cross-db compatibility reasons, the script should use the `$DB->sql_like()` and `$DB->sql_like_escape()` methods.

**Comment by eLearnTK** [comment]
SQL- Injection fixed:
$table   = 'course_categories';
$select  = $DB->sql_like('name', ':search', $casesensitive = false);
$param   = array('search' => '%'.$search.'%');
$records = $DB->get_records_select($table, $select, $param);

**Comment by eLearnTK** [comment]
SQL- Injection fixed:
$table = 'course_categories';
$select = $DB->sql_like('name', ':search', $casesensitive = false);
$param = array('search' => '%'.$search.'%');
$records = $DB->get_records_select($table, $select, $param);
